### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ubx** [hor63/horOpenVario#1] opened 2019-06-13 17:12 UTC
Hi

When I try to create the image, I get the following compile error:

=====
andreas@andreas-iMac:~/ClionProjects/horOpenVario$ ./makenewimage.sh
 BASEDIR = /home/andreas/ClionProjects/horOpenVario
 
Selection of distributions which can be installed.
Enter:
  a - Artful
  b - Bionic - LTS (default)
  x - Xenial - LTS

Selected distribution is bionic
rebuild uboot
 O = /home/andreas/ClionProjects/horOpenVario/build/u-boot
make[1]: Entering directory '/home/andreas/ClionProjects/horOpenVario/build/u-boot'
  CHK     include/config/uboot.release
  Using /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline as source for U-Boot
  GEN     ./Makefile
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
  HOSTCC  tools/mkenvimage.o
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/aisimage.o
In file included from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/tools/../include/../lib/libfdt/libfdt.h:10,
                 from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/tools/../include/libfdt.h:1,
                 from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/tools/fdt_host.h:11,
                 from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/tools/imagetool.h:24,
                 from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/tools/aisimage.c:8:
/usr/include/libfdt_env.h:71:30: error: conflicting types for ‘fdt64_t’
 typedef uint64_t FDT_BITWISE fdt64_t;
                              ^~~~~~~
In file included from <command-line>:
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/libfdt_env.h:19:16: note: previous declaration of ‘fdt64_t’ was here
 typedef __be64 fdt64_t;
                ^~~~~~~
In file included from /home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/libfdt_env.h:12,
                 from <command-line>:
/usr/include/libfdt_env.h:91:24: error: expected ‘)’ before ‘x’
 static inline uint32_t fdt32_to_cpu(fdt32_t x)
                        ^~~~~~~~~~~~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:9: error: expected ‘)’ before ‘&’ token
  ((((x) & 0xff000000) >> 24) | \
         ^
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:23: error: expected ‘)’ before ‘>>’ token
  ((((x) & 0xff000000) >> 24) | \
                       ^~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:30: error: expected ‘)’ before ‘|’ token
  ((((x) & 0xff000000) >> 24) | \
                              ^
/usr/include/libfdt_env.h:95:23: error: expected ‘)’ before ‘x’
 static inline fdt32_t cpu_to_fdt32(uint32_t x)
                       ^~~~~~~~~~~~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:9: error: expected ‘)’ before ‘&’ token
  ((((x) & 0xff000000) >> 24) | \
         ^
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:23: error: expected ‘)’ before ‘>>’ token
  ((((x) & 0xff000000) >> 24) | \
                       ^~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:71:30: error: expected ‘)’ before ‘|’ token
  ((((x) & 0xff000000) >> 24) | \
                              ^
/usr/include/libfdt_env.h:100:24: error: expected ‘)’ before ‘x’
 static inline uint64_t fdt64_to_cpu(fdt64_t x)
                        ^~~~~~~~~~~~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:9: error: expected ‘)’ before ‘&’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
         ^
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:36: error: expected ‘)’ before ‘>>’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
                                    ^~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:43: error: expected ‘)’ before ‘|’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
                                           ^
/usr/include/libfdt_env.h:104:23: error: expected ‘)’ before ‘x’
 static inline fdt64_t cpu_to_fdt64(uint64_t x)
                       ^~~~~~~~~~~~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:9: error: expected ‘)’ before ‘&’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
         ^
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:36: error: expected ‘)’ before ‘>>’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
                                    ^~
/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/include/compiler.h:76:43: error: expected ‘)’ before ‘|’ token
  ((((x) & 0xff00000000000000##sfx) >> 56) | \
                                           ^
make[2]: *** [scripts/Makefile.host:116: tools/aisimage.o] Error 1
make[1]: *** [/home/andreas/ClionProjects/horOpenVario/src/uboot-mainline/Makefile:1279: tools] Error 2
make[1]: Leaving directory '/home/andreas/ClionProjects/horOpenVario/build/u-boot'
make: *** [Makefile:150: sub-make] Error 2
andreas@andreas-iMac:~/ClionProjects/horOpenVario$ 

====
andreas@andreas-iMac:~/ClionProjects/horOpenVario$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 

====
andreas@andreas-iMac:~/ClionProjects/horOpenVario$ uname -a
Linux andreas-iMac 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hor63** [comment] 2019-06-14 12:04
You are obviously using a newer Ubuntu version than I am (18.04 LTS).
Please apply in the iterim the patch described here http://lists.busybox.net/pipermail/buildroot/2018-March/215420.html locally. I will fix it in the repository some time next week.

**Comment by hor63** [comment] 2019-06-14 15:16
The issue is fixed with commit [118171d](https://github.com/hor63/horOpenVario/commit/118171d382ba720fa0bedff6081e20ec52ad7f2f)
Please perform 
`git pull --recurse-submodules`

**Closed as completed by hor63** 2019-06-14 15:16 UTC
Labels: bug

**Comment by ubx** [comment] 2019-06-14 16:55
I'm on a Ubuntu 19.04 box. I was now able to generate a SD image.
Thanks a lot.
